export default {
  SET_NEWS: "SET_NEWS",
  SET_SERVICES: "SET_SERVICES",
  SET_TABLES: "SET_TABLES",
  FILTER_LATEST: "FILTER_LATEST",
  FILTER_OLDEST: "FILTER_OLDEST",
  FILTER_FORMAT: "FILTER_FORMAT",

};
